export const APP_KEYS = {
  USER_SURVEYS: "USER_SURVEYS",
  RESPONDENT_DATA: "RESPONDENT_DATA",
  COUNTRY_FLAG: "COUNTRY_FLAG",
  AVAILABLE_SURVEYS: "AVAILABLE_SURVEYS",
  APPLY_SURVEYS: "APPLY_SURVEYS",
  APPLICATION_SURVEYS: "APPLICATION_SURVEYS",
  UNRESTRICTED_BALANCE: "UNRESTRICTED_BALANCE",
  TOTAL_RESPONDENTS: "TOTAL_RESPONDENTS",
  LOGIN_STREAK: "LOGIN_STREAK",
};
