apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pollsensei-web-monitor
  namespace: release-pollsensei-web
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: pollsensei-web-app
  namespaceSelector:
    matchNames:
      - release-pollsensei-web
  endpoints:
    - port: http
      interval: 30s
